kind: pipeline
type: docker
name: publish

trigger:
  branch:
    - master

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build
    image: betterweb/hugo
    commands:
      - npm i
      - HUGO_ENVIRONMENT=production hugo --gc

  - name: deploy
    image: instrumentisto/rsync-ssh
    commands:
      - echo "$PRIVATE_KEY" >> id_rsa
      - chmod 600 id_rsa
      - cd public
      - rsync -avz --delete -e 'ssh -i ../id_rsa -o StrictHostKeyChecking=no' --progress ./* tsims@tres-sims.com:/opt/tres-sims/
    environment:
      PRIVATE_KEY:
        from_secret: PRIVATE_KEY
