baseurl = "https://tres-sims.com"
metaDataFormat = "yaml"
title = "Tres Sims"
theme = "blist"
googleAnalytics = "G-EZJJXQ8M60"

# [languages]
#   [languages.en]
#     contentDir = "content/" #English
#     weight = 1
#     languageName = "English"
#     [languages.en.params]
#       introTitle = "Hey! I'm Tres Sims"
#       introSubtitle = "Computer Graphics Tools Artist"
#       introPhoto = "/picture.jpg"
#       logo = "/blist-logo.png"
#     [[languages.en.menu.main]]
#         name = "Blog"
        # url = "blog"
#         weight = 1

#     [[languages.en.menu.main]]
#         name = "About"
#         url = "page/about/"
#         weight = 2

#     [[languages.en.menu.main]]
#         name = "Tags"
#         url = "tags"
#         weight = 3

#     [[languages.en.menu.main]]
#         name = "Top Post"
#         url = "/en/blog/emoji-support/"
#         weight = 4

[params]
   # Basic Parameters
   introTitle = "Hey! I'm Tres Sims"
   introSubtitle = "Software and Hardware technology engineer with broad integration experience.  Adept full-stack web developer using multiple industry standards including React JS, Python, Postgresql, and others.  Passionate constructor of scalable solutions for account management, helpdesk support, VR/3D integration, additive production, and network administration.  Accomplished custom mobile application developer in Java."
   introPhoto = "/picture.jpg"
   logo = "/logo.png"

  # Enable the darkmode toggle in header
  darkModeToggle = false

  # Enable search in header
  enableSearch = true

  # Enable floating return to top widget
  enableFloatingReturnToTop = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Tres Sims · All rights reserved"
  favicon = "/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"
  hilightColor = "teal-400"

  # The page bundles that are shown on the front page
  bundles = ["Projects"]

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I've got interesting work shared across all my socials"

  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://linkedin.com/in/tres-sims"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/TresSims"
  # [[params.homepage.social.icons]]
  #   website = "youtube"
  #   url = "https://youtube.com"
  # [[params.homepage.social.icons]]
  #   website = "instagram"
  #   url = "https://instagram.com/tsims.95"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
